### ISSUE TITLE
QtMEL for QML

### ISSUE THREAD

**Issue by ofuochi** [kibsoft/QtMEL#33]
Hi. you've done a great Job here, well done! Am doing a UI intensive project with QML and I'm on a window 7 64bits platform. Is there a way for QML people to enjoy this? (Am very weak with C++)
As you might know, Video recording is not supported for Windows in QML either. It will really be helpful if there is.

**Comment by kibsoft** [comment]
Hello! Unfortunately I don't have implementation available directly in QML. But that is what you can do:
1) create object of Recorder class in main.cpp(for example)
2) set image and audio grabber to Recorder using setImageGrabber and setAudioGrabber
3) expose Recorder into QML using setContextProperty (look at http://doc.qt.io/qt-5/qtqml-cppintegration-contextproperties.html)
4) Use Recorder's slots like start(), stop(), pause(), resume() in QML

**Comment by ofuochi** [comment]
Thank you so much. I'll try that right now!
